name: Copilot Metrics & Seat Management Report 

credentials:
  github-token: "ghp_1234567890abcdefghijklmnopqrstuvwxyz1234"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - TCDD-4368-copilot-usage
jobs: 
  run:
    name: Copilot Usage Metrics Export Action // Name of the job 
    runs-on: ubuntu-latest 
    steps:
      - uses: bcg-ep-dso/github-action-composite-actions/CopilotMetricsSeatReport@copilot-usage 
